// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_orders_default = defineTool({
  name: "list_orders",
  title: "List orders",
  description: "List recent logistics orders from the control tower, optionally filtered by status.",
  inputSchema: {
    status: z.string().optional().describe("Optional order status filter, e.g. pending, in_transit, delivered."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of orders to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }) => {
    const supabase = anonClient();
    let query = supabase.from("orders").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_order_default = defineTool2({
  name: "get_order",
  title: "Get order",
  description: "Fetch a single order (with its items and tracking events) by order id or order number.",
  inputSchema: {
    id: z2.string().optional().describe("Order UUID."),
    order_number: z2.string().optional().describe("Human-readable order number.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, order_number }) => {
    if (!id && !order_number) {
      return {
        content: [{ type: "text", text: "Provide either id or order_number." }],
        isError: true
      };
    }
    const supabase = anonClient2();
    let query = supabase.from("orders").select("*, order_items(*), order_tracking_events(*)").limit(1);
    query = id ? query.eq("id", id) : query.eq("order_number", order_number);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Order not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function anonClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_alerts_default = defineTool3({
  name: "list_alerts",
  title: "List alerts",
  description: "List recent logistics alerts, optionally filtered by severity or status.",
  inputSchema: {
    severity: z3.string().optional().describe("Filter by severity, e.g. low, medium, high, critical."),
    status: z3.string().optional().describe("Filter by status, e.g. active, resolved."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ severity, status, limit }) => {
    const supabase = anonClient3();
    let query = supabase.from("alerts").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (severity) query = query.eq("severity", severity);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lp-control-tower-mcp",
  title: "LP Control Tower MCP",
  version: "0.1.0",
  instructions: "Read-only access to the LP Control Tower logistics platform. Use list_orders and get_order to inspect shipment orders and their items/tracking events, and list_alerts to review recent operational alerts.",
  tools: [list_orders_default, get_order_default, list_alerts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
