// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvrnufiqmqcziqpnehyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cm51ZmlxbXFjemlxcG5laHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODY3MjIsImV4cCI6MjA2OTQ2MjcyMn0.3Ahze-QxOUxtSlowxiOzG7Knh2oLeiYc6EXe9klt3Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});